const iconNames = {
  ArrowLeftOutlined: ["arrow-left", "faArrowLeft"],
  ArrowRightOutlined: ["arrow-right", "faArrowRight"],
  BarsOutlined: ["bars", "faBars"],
  CalendarOutlined: ["calendar", "faCalendar"],
  CaretDownFilled: ["caret-down", "faCaretDown", "filled"],
  CaretDownOutlined: ["caret-down", "faCaretDown"],
  CaretLeftFilled: ["caret-left", "faCaretLeft", "filled"],
  CaretRightFilled: ["caret-right", "faCaretRight", "filled"],
  CaretUpFilled: ["caret-up", "faCaretUp", "filled"],
  CaretUpOutlined: ["caret-left", "faCaretUp"],
  CheckCircleFilled: ["check-circle", "faCircleCheck", "filled"],
  CheckCircleOutlined: ["check-circle", "faCircleCheck"],
  CheckOutlined: ["check", "faCheck"],
  ClockCircleOutlined: ["check-circle", "faCircleCheck"],
  CloseCircleFilled: ["close-circle", "faCircleXmark", "filled"],
  CloseCircleOutlined: ["close-circle", "faCircleXmark"],
  CloseOutlined: ["close", "faXmark"],
  CopyOutlined: ["copy", "faCopy"],
  DeleteOutlined: ["delete", "faTrash"],
  DoubleLeftOutlined: ["double-left", "faAnglesLeft"],
  DoubleRightOutlined: ["double-right", "faAnglesRight"],
  DownloadOutlined: ["download", "faDownload"],
  DownOutlined: ["down", "faAngleDown"],
  EditOutlined: ["edit", "faPencil"],
  EllipsisOutlined: ["ellipsis", "faEllipsis"],
  EnterOutlined: ["enter", "faTurnDownLeft"],
  ExclamationCircleFilled: ["exclamation-circle", "faCircleExclamation"],
  ExclamationCircleOutlined: ["exclamation-circle", "faCircleExclamation"],
  EyeInvisibleOutlined: ["eye-invisible", "faEyeSlash"],
  EyeOutlined: ["eye", "faEye"],
  FileOutlined: ["file", "faFile"],
  FileTwoTone: ["file", "faFile", "two-tone"],
  FilterFilled: ["filter", "faFilter", 'filled'],
  FolderOpenOutlined: ["folder-open", "faFolderOpen"],
  FolderOutlined: ["folder", "faFolder"],
  HolderOutlined: ["holder", "faGripDotsVertical"],
  InfoCircleFilled: ["info-circle", "faCircleInfo"],
  InfoCircleOutlined: ["info-circle", "faCircleInfo"],
  LeftOutlined: ["left", "faAngleLeft"],
  LoadingOutlined: ["loading", "faSpinner"],
  MinusSquareOutlined: ["minus-square", "faSquareMinus"],
  PaperClipOutlined: ["paper-clip", "faPaperclip"],
  PictureTwoTone: ["picture", "faImage", "two-tone"],
  PlusOutlined: ["plus", "faPlus"],
  PlusSquareOutlined: ["plus-square", "faSquarePlus"],
  RedoOutlined: ["redo", "faArrowRotateRight"],
  RightOutlined: ["right", "faAngleRight"],
  SearchOutlined: ["search", "faMagnifyingGlass"],
  StarFilled: ["star", "faStar"],
  UpOutlined: ["up", "faAngleUp"],
  WarningFilled: ["warning", "faTriangleExclamation"],
};

module.exports = iconNames;
