export const iconNames = {
  ArrowLeftOutlined: { name: "arrow-left", ti: "arrow-left" },
  ArrowRightOutlined: { name: "arrow-right", ti: "arrow-right" },
  BarsOutlined: { name: "bars", ti: "menu-2" },
  CalendarOutlined: { name: "calendar", ti: "calendar-week" },
  CaretDownFilled: {
    name: "caret-down",
    ti: "caret-down",
    theme: "filled",
  },
  CaretDownOutlined: { name: "caret-down", ti: "caret-down" },
  CaretLeftFilled: {
    name: "caret-left",
    ti: "caret-left",
    theme: "filled",
  },
  CaretRightFilled: {
    name: "caret-right",
    ti: "caret-right",
    theme: "filled",
  },
  CaretUpFilled: { name: "caret-up", ti: "caret-up", theme: "filled" },
  CaretUpOutlined: { name: "caret-left", ti: "caret-up" },
  CheckCircleFilled: {
    name: "check-circle",
    ti: "circle-check",
    theme: "filled",
  },
  CheckCircleOutlined: { name: "check-circle", ti: "circle-check" },
  CheckOutlined: { name: "check", ti: "check" },
  ClockCircleOutlined: { name: "clock-circle", ti: "clock" },
  CloseCircleFilled: {
    name: "close-circle",
    ti: "circle-x",
    theme: "filled",
  },
  CloseCircleOutlined: { name: "close-circle", ti: "circle-x" },
  CloseOutlined: { name: "close", ti: "x" },
  CopyOutlined: { name: "copy", ti: "copy" },
  DeleteOutlined: { name: "delete", ti: "trash" },
  DoubleLeftOutlined: { name: "double-left", ti: "chevrons-left" },
  DoubleRightOutlined: { name: "double-right", ti: "chevrons-right" },
  DownloadOutlined: { name: "download", ti: "download" },
  DownOutlined: { name: "down", ti: "chevron-down" },
  EditOutlined: { name: "edit", ti: "edit" },
  EllipsisOutlined: { name: "ellipsis", ti: "dots" },
  EnterOutlined: { name: "enter", ti: "corner-down-left" },
  ExclamationCircleFilled: {
    name: "exclamation-circle",
    ti: "exclamation-circle",
    theme: "filled",
  },
  ExclamationCircleOutlined: {
    name: "exclamation-circle",
    ti: "exclamation-circle",
  },
  EyeInvisibleOutlined: { name: "eye-invisible", ti: "eye-off" },
  EyeOutlined: { name: "eye", ti: "eye" },
  FileOutlined: { name: "file", ti: "file" },
  FileTwoTone: { name: "file", ti: "file", theme: "filled" },
  FilterFilled: { name: "filter", ti: "filter", theme: "filled" },
  FolderOpenOutlined: { name: "folder-open", ti: "folder-open" },
  FolderOutlined: { name: "folder", ti: "folder" },
  HolderOutlined: { name: "holder", ti: "dots-vertical" },
  InfoCircleFilled: {
    name: "info-circle",
    ti: "info-circle",
    theme: "filled",
  },
  InfoCircleOutlined: { name: "info-circle", ti: "info-circle" },
  LeftOutlined: { name: "left", ti: "arrow-left" },
  LoadingOutlined: { name: "loading", ti: "loader-2" },
  MinusSquareOutlined: { name: "minus-square", ti: "chevron-down" },
  PaperClipOutlined: { name: "paper-clip", ti: "paperclip" },
  PictureTwoTone: { name: "picture", ti: "photo", theme: "two-tone" },
  PlusOutlined: { name: "plus", ti: "plus" },
  PlusSquareOutlined: { name: "plus-square", ti: "square-plus" },
  RedoOutlined: { name: "redo", ti: "arrow-forward-up" },
  RightOutlined: { name: "right", ti: "arrow-right" },
  SearchOutlined: { name: "search", ti: "search" },
  StarFilled: { name: "star", ti: "star", theme: "filled" },
  UpOutlined: { name: "up", ti: "arrow-up" },
  WarningFilled: {
    name: "warning",
    ti: "alert-triangle",
    theme: "filled",
  },
};
