const iconNames = {
  ArrowLeftOutlined: { name: "arrow-left", fa: "faArrowLeft" },
  ArrowRightOutlined: { name: "arrow-right", fa: "faArrowRight" },
  BarsOutlined: { name: "bars", fa: "faBars" },
  CalendarOutlined: { name: "calendar", fa: "faCalendar" },
  CaretDownFilled: { name: "caret-down", fa: "faCaretDown", theme: "filled" },
  CaretDownOutlined: { name: "caret-down", fa: "faCaretDown" },
  CaretLeftFilled: { name: "caret-left", fa: "faCaretLeft", theme: "filled" },
  CaretRightFilled: {
    name: "caret-right",
    fa: "faCaretRight",
    theme: "filled",
  },
  CaretUpFilled: { name: "caret-up", fa: "faCaretUp", theme: "filled" },
  CaretUpOutlined: { name: "caret-left", fa: "faCaretUp" },
  CheckCircleFilled: {
    name: "check-circle",
    fa: "faCircleCheck",
    theme: "filled",
  },
  CheckCircleOutlined: { name: "check-circle", fa: "faCircleCheck" },
  CheckOutlined: { name: "check", fa: "faCheck" },
  ClockCircleOutlined: { name: "check-circle", fa: "faCircleCheck" },
  CloseCircleFilled: {
    name: "close-circle",
    fa: "faCircleXmark",
    theme: "filled",
  },
  CloseCircleOutlined: { name: "close-circle", fa: "faCircleXmark" },
  CloseOutlined: { name: "close", fa: "faXmark" },
  CopyOutlined: { name: "copy", fa: "faCopy" },
  DeleteOutlined: { name: "delete", fa: "faTrash" },
  DoubleLeftOutlined: { name: "double-left", fa: "faAnglesLeft" },
  DoubleRightOutlined: { name: "double-right", fa: "faAnglesRight" },
  DownloadOutlined: { name: "download", fa: "faDownload" },
  DownOutlined: { name: "down", fa: "faAngleDown" },
  EditOutlined: { name: "edit", fa: "faPencil" },
  EllipsisOutlined: { name: "ellipsis", fa: "faEllipsis" },
  EnterOutlined: { name: "enter", fa: "faTurnDown", rotate: 90 },
  ExclamationCircleFilled: {
    name: "exclamation-circle",
    fa: "faCircleExclamation",
  },
  ExclamationCircleOutlined: {
    name: "exclamation-circle",
    fa: "faCircleExclamation",
  },
  EyeInvisibleOutlined: { name: "eye-invisible", fa: "faEyeSlash" },
  EyeOutlined: { name: "eye", fa: "faEye" },
  FileOutlined: { name: "file", fa: "faFile" },
  FileTwoTone: { name: "file", fa: "faFile", theme: "two-tone" },
  FilterFilled: {name:"filter", fa:"faFilter", theme:"filled"},
  FolderOpenOutlined: { name: "folder-open", fa: "faFolderOpen" },
  FolderOutlined: { name: "folder", fa: "faFolder" },
  HolderOutlined: { name: "holder", fa: "faEllipsisVertical" },
  InfoCircleFilled: { name: "info-circle", fa: "faCircleInfo" },
  InfoCircleOutlined: { name: "info-circle", fa: "faCircleInfo" },
  LeftOutlined: { name: "left", fa: "faAngleLeft" },
  LoadingOutlined: { name: "loading", fa: "faSpinner" },
  MinusSquareOutlined: { name: "minus-square", fa: "faSquareMinus" },
  PaperClipOutlined: { name: "paper-clip", fa: "faPaperclip" },
  PictureTwoTone: { name: "picture", fa: "faImage", theme: "two-tone" },
  PlusOutlined: { name: "plus", fa: "faPlus" },
  PlusSquareOutlined: { name: "plus-square", fa: "faSquarePlus" },
  RedoOutlined: { name: "redo", fa: "faArrowRotateRight" },
  RightOutlined: { name: "right", fa: "faAngleRight" },
  SearchOutlined: { name: "search", fa: "faMagnifyingGlass" },
  StarFilled: { name: "star", fa: "faStar" },
  UpOutlined: { name: "up", fa: "faAngleUp" },
  WarningFilled: { name: "warning", fa: "faTriangleExclamation" },
};

module.exports = iconNames;
